apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: web-app
data:
  user_info.sql: |
    CREATE TABLE user_info (
      `ID` int(6) UNSIGNED NOT NULL,
      `First_name` varchar(30) DEFAULT NULL,
      `Last_name` varchar(30) DEFAULT NULL,
      `Username` varchar(30) DEFAULT NULL,
      `Email` varchar(50) DEFAULT NULL,
      `Password` varchar(50) DEFAULT NULL
    );

    ALTER TABLE user_info ADD PRIMARY KEY (`ID`);

    ALTER TABLE user_info MODIFY `ID` int(6) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

  courses.sql: |
    CREATE TABLE courses (
      `id` int(6) NOT NULL,
      `user_id` int(6) NOT NULL,
      `course_name` varchar(255) NOT NULL
    );

    ALTER TABLE courses ADD PRIMARY KEY (`id`);

    ALTER TABLE courses MODIFY `id` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;