---
- name: Install and set up Jenkins
  hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
    - name: update_cache=yes
      apt:
        update_cache: yes

    - name: Install Java, default-jre and gnupg
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - default-jre
        - openjdk-11-jdk
        - gnupg
        - apt-transport-https
        - wget
        - gnupg
        - software-properties-common
        - curl
  
    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
  
    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: add PPA using command
      command: echo "deb https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list

    - name: Update apt cache
      apt:
        update_cache: yes
  
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
  
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Add Hashicorp GPG key
      command: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add Hashicorp repository
      command: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Get Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Print Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password is {{ jenkins_password.stdout }}"
      when: jenkins_password.stdout != ""

    - name: Install Docker
      apt:
        name: docker.io
        state: present