pipeline {
    agent any
    environment {
       DO_TOKEN = credentials('do_token')
       KUBECONFIG = '/var/lib/jenkins/workspace/provisioning_cluster/01-terraform/kubeconfig.yaml'
       SERVICE = 'nginx-ingress-ingress-nginx-controller'
    }
    stages {
        stage('delete ingress controller') {
            steps {
                sh '''
                kubectl delete -n default service nginx-ingress-ingress-nginx-controller
                '''
            }
        }
        stage('terrorm destroy DNS') {
            steps {
                dir('05-terraform/terraform') {
                sh '''
                terraform destroy -auto-approve -var DO_TOKEN=${DO_TOKEN} -var nginx_ip=$LOAD_BALANCER_IP -auto-approve
                '''
                }
             }
        }
        stage('terraform destroy cluster') {
            steps {
                dir('01-terraform') {
                sh '''
                terraform destroy -auto-approve -var DO_TOKEN=${DO_TOKEN}
                '''
                }
             }
        }
    }
}