pipeline {
    agent any
    environment {
        DO_TOKEN = credentials('do_token')
    }
    stages {
        stage('destroy cluster') {
            steps {
                dir('./01-terraform') {
                    sh '''
                    terraform init
                    terraform destroy -auto-approve -var DO_TOKEN=${DO_TOKEN}
                    '''
                }
             }
         }

         stage('Destroy DNS') {
            steps {
                dir('05-terraform/terraform') {
                    sh '''
                    terraform init
                    terraform destroy -auto-approve -var DO_TOKEN=${DO_TOKEN}
                    '''
                }
             }
         }
 
     }
}
