# Docker compose file to run webapp and mysql database

version: '3'
services:
  web:
   image: broekeson/web-app
   ports:
    - "80:80"
   depends_on:
    - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: altschool
    volumes:
      - ./mysql:/var/lib/mysql
      - ../initdb:/docker-entrypoint-initdb.d
