pipeline {
    agent any
    environment {
       DO_TOKEN = credentials('do_token')
       KUBECONFIG = '/var/lib/jenkins/workspace/provisioning_cluster/01-terraform/kubeconfig.yaml'
       SERVICE = 'nginx-ingress-ingress-nginx-controller'
    }
    stages {
       stage('Get External IP') {
        steps {
          dir('05-terraform/terraform') {
           script {
             sh '''
             LOAD_BALANCER_IP=$(kubectl get svc $SERVICE -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
             terraform init
             terraform apply  -var DO_TOKEN=${DO_TOKEN} -var nginx_ip=$LOAD_BALANCER_IP -auto-approve
             '''
           }  
          }
         }
       }
    }
}
