pipeline {
    agent any
    environment {
       DO_TOKEN = credentials('do_token')
       KUBECONFIG = '/var/lib/jenkins/workspace/provisioning_cluster/01-terraform/kubeconfig.yaml'
    }
    stages {
       stage('Get External IP') {
        steps {
          dir('05-terraform/terraform') {
           script {
             sh '''
             terraform init
             terraform apply  -var DO_TOKEN=${DO_TOKEN}  -auto-approve
             '''
           }  
          }
         }
       }
       stage("Get External IP") {
        steps {
          dir('05-terraform/terraform') {
           script {
             sh '''
             terraform output -json | jq -r '.external_ip.value'
             '''
           }  
          }
         }
       }
    }
}
