pipeline {
    agent any

    environment {
        KUBECONFIG = '/var/lib/jenkins/workspace/altschool/01-terraform/kubeconfig.yaml'
    }

    stages {
        stage('authenticate') {
            steps {
                sh '''
                curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
                helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
                helm repo update
                helm install nginx-ingress ingress-nginx/ingress-nginx
                '''
            }
        }
        
        stage('deploy') {
          steps {
              dir('02-k8s-web-app') {
              sh '''
              kubectl apply -f secret.yaml
              kubectl apply -f configMap.yaml
              kubectl apply -f a-namespace.yaml
              kubectl apply -f db-deployment.yaml
              kubectl apply -f db-service.yaml
              kubectl apply -f web-app-deployment.yaml
              kubectl apply -f web-app-service.yaml
              '''
              }
          }
      }
    } 
}
