apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        command: ["sh", "-c", "mysql -u root -p${MYSQL_ROOT_PASSWORD} < ../initdb/create-tables.sql"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: database
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: ../initdb/create-tables.sql
      volumes:
      - name: db-data
        emptyDir: {}
      - name: mysql-config
        configMap:
          name: mysql-config
    
