pipeline {
    agent any
    environment {
       DO_TOKEN = credentials('do_token')
       KUBECONFIG = '/var/lib/jenkins/workspace/provisioning_cluster/01-terraform/kubeconfig.yaml'
       SERVICE = 'nginx-ingress-ingress-nginx-controller'
       DNS = 'ekene.tech' 
    }
    stages {
       stage('Get External IP') {
           script {
             sh '''

             '''
        }  
      }
    }
  }